### ISSUE TITLE
1. Cash only

### ISSUE THREAD

**Issue by Idris01** [Idris01/AirBnB_clone_v4#2]
Write a script that starts a Flask web application:

- Based on web_flask, copy: web_flask/static, web_flask/templates/100-hbnb.html, web_flask/__init__.py and web_flask/100-hbnb.py into the web_dynamic folder
- Rename 100-hbnb.py to 0-hbnb.py
- Rename 100-hbnb.html to 0-hbnb.html
- Update 0-hbnb.py to replace the existing route to /0-hbnb/

**Comment by Huming-bird** [comment]
This is done on both ends. i am closing this
